name: React App CI/CD with Cypress and Launchable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies (including Cypress)
      - name: Install dependencies
        run: npm install
         # Step 4: Start React app in the background
      - name: Build Next.js
        run: npm run build

      - name: Start Next.js Server
        run: npm run start &
        
      # Step 5: Wait for React App to be ready
      - name: Wait for React App
        run: npx wait-on http://localhost:3000

      # Step 4: Set up Python for Launchable integration
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 5: Install Launchable Python package
      - name: Install Launchable Python package
        run: |
          pip install --upgrade pip
          pip install --user --upgrade launchable

      # Step 6: Verify Cypress installation
      - name: Verify Cypress Installation
        run:  npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --spec 'cypress/e2e/launchTest.cy.jsx'


      # Step 10: Record Build in Launchable
      - name: Record Build
        run: launchable record build --name ${{ github.sha }}

      # Step 11: Optimize Tests with Launchable (If needed for a subset of tests)
      # This step is used if you want to run a subset of tests based on previous analysis
      - name: Optimize Tests with Launchable
        run: |
          launchable subset --target 50% --base-path ./cypress/e2e > subset.txt
          npx cypress run --spec $(cat subset.txt)

      # Step 12: Record Test Results in Launchable
      - name: Record Test Results
        run: launchable record tests cypress --base-path ./cypress/e2e --session $(cat .launchable_session)

      # Step 13: Deploy React App (Optional)
      - name: Deploy React App (Optional)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
